package com.example.gedune.bookcollection.orm;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.gedune.bookcollection.Bean.BookDetail;

import com.example.gedune.bookcollection.orm.BookDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDetailDaoConfig;

    private final BookDetailDao bookDetailDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDetailDaoConfig = daoConfigMap.get(BookDetailDao.class).clone();
        bookDetailDaoConfig.initIdentityScope(type);

        bookDetailDao = new BookDetailDao(bookDetailDaoConfig, this);

        registerDao(BookDetail.class, bookDetailDao);
    }
    
    public void clear() {
        bookDetailDaoConfig.clearIdentityScope();
    }

    public BookDetailDao getBookDetailDao() {
        return bookDetailDao;
    }

}
